### PR TITLE
Fix SeekLowerBound where tree contains keys that are prefixes of each other

### LINKED ISSUE #37: SeekLowerBound not working correctly
I was trying to replace our custom `Seek` behavior in my fork with `SeekLowerBound` described in here https://github.com/hashicorp/go-immutable-radix/pull/29#issuecomment-627942830 but hit some issues.

First thing I discovered was that an empty key (root) confuses the seeker. Tried to fix this in https://github.com/hashicorp/go-immutable-radix/commit/30c53379998b3a3fc23b26088546e455d5cd25f4

But then I discovered some more cases that behave weirdly. Added tests for them in https://github.com/hashicorp/go-immutable-radix/commit/5bed3aa0fa9f25207cbbe490ebc97ce18aeae6d2

```
    --- FAIL: TestIterateLowerBound/case015 (0.00s)
        iradix_test.go:1712: keys=[ aaa bbb] search=aa want=[aaa bbb]
        iradix_test.go:1730: mis-match: key=aa
              got=[]
              want=[aaa bbb]
    --- FAIL: TestIterateLowerBound/case016 (0.00s)
        iradix_test.go:1712: keys=[ aaa bbb] search=aaab want=[bbb]
        iradix_test.go:1730: mis-match: key=aaab
              got=[]
              want=[bbb]
    --- PASS: TestIterateLowerBound/case017 (0.00s)
        iradix_test.go:1712: keys=[ aaa bbb] search= want=[ aaa bbb]
    --- FAIL: TestIterateLowerBound/case018 (0.00s)
        iradix_test.go:1712: keys=[a aa bbb] search=aa want=[aa bbb]
        iradix_test.go:1730: mis-match: key=aa
              got=[bbb]
              want=[aa bbb]
    --- FAIL: TestIterateLowerBound/case019 (0.00s)
        iradix_test.go:1712: keys=[a aaa bbb] search=aa want=[aaa bbb]
        iradix_test.go:1730: mis-match: key=aa
              got=[bbb]
              want=[aaa bbb]
```

@banks @thaJeztah

### PR DESCRIPTION
**Pull request by banks**
Fixes #37 #28.

This seems like a trivial case to miss however it stemmed from some confusion (on my part) about whether iradix was ever intended to support keys that were prefixes. It's a long story and I don't even recall exactly why I thought this was the case now given that every other operation on iradix supports this and most even include this case in their test examples. We even had it in the README example!

But some combination of:
 - I was working at the time on a related radix tree that did have the assumption of null-terminated keys
 - hashicorp/go-memdb always null terminates even for simpler string indexes

Anyway the fix is simple and the examples now pass.

In addition the fuzz test (which explicitly used the null-termination trick to never trigger this assuming it was necessary in general) now passes without null terminating keys every time I've run it.

### CODE REVIEW

**Review by ncabatoff — APPROVED** [review]
Nice find!

**Comment by banks** [comment]
There are at least a couple of other issues here I'm working on:

 - there is code that looks like it could cause a panic by referencing `search[0]` right after a conditional branch that sets `search = []byte{}`. It turns out that condition is unreachable so I'll remove it.
 - I missed `SeekReverseIterator` which has similar issues - I assumed because tests passed it was OK but in fact it only has fuzz tests for lower bound which happened not to provoke this issue any time I ran them. I'm adding table tests and finding that more is needed to not just fix this bad assumption but to also return results in the reversed order!

I'll update this PR when done. Thanks for the review @ncabatoff!

File: iradix_test.go [hunk 1]
```diff
@@ -1725,17 +1750,15 @@ func TestIterateLowerBoundFuzz(t *testing.T) {
...
-	// tree (with a null byte appended since our tree doesn't support one key
-	// being a prefix of another and treats null bytes specially).
+	// tree.
 	//
 	// It also maintains a plain sorted list of the same set of keys and asserts
 	// that iterating from some random key to the end using LowerBound produces
 	// the same list as filtering all sorted keys that are lower.
 
 	radixAddAndScan := func(newKey, searchKey readableString) []string {
 		// Append a null byte
```
Comment (thaJeztah) [inline iradix_test.go]: Looks like the comment also needs to be removed

Comment (thaJeztah) [reply iradix_test.go]: oh! think it's removed in the second commit 🤦

**Comment by tonistiigi** [comment]
This seems to fix the issues in buildkit tests https://github.com/moby/buildkit/pull/2182 . Thanks!

Does this also close #35 ?

**Comment by banks** [comment]
> Does this also close #35 ?

It should do once I'm done here. Thanks for pointing that out I'd missed it!

**Comment by banks** [comment]
I think with the most recent commit this PR now includes:

 - [x] Support keys that are prefixes of each other in `Iterator.SeekLowerBound`
 - [x] Support keys that are prefixes of each other in `ReverseIterator.SeekReverseLowerBound`
 - [x] Remove cases that could cause a panic in both `SeekLowerBound` and `SeekReverseLowerBound`
 - [x] Add test examples for both above issues and both directions that provoked the issues reported. Also added a bunch of other examples that were bugs found while reading the code/reasoning about it.
 - [x] Make all the `*LowerBound` fuzz tests not append null bytes.

I'd say I'm reasonably confident that this is now _more_ correct than before. I'd not be super surprised if there are still examples that could be found that cause it to break! The many examples I found manually that our fuzz tests have not yet shows that they are certainly not exhaustive currently.

File: iter.go [hunk 2]
```diff
@@ -87,6 +87,16 @@ func (i *Iterator) SeekLowerBound(key []byte) {
 		i.stack = append(i.stack, edges{edge{node: n}})
 	}
 
+	findMin := func(n *Node) {
+		n = i.recurseMin(n)
+		if n != nil {
+			found(n)
+			return
+		}
+		i.node = nil
```
Comment (ncabatoff) [inline iter.go:96]: Would it be worth adding a comment to the top of the function explaining how `i.node` and `i.stack` should be affected by the different outcomes that may occur?  e.g.:stack will be traversed by Next.  Since stack is non-nil, node will not be used by Next, only by future Seek calls.  We set node = nil when we want to indicate that that there is no lower bound.

I'm actually not clear why we set node=nil - isn't leaving stack empty enough?  It feels like an extra side effect that's not very obvious to the user.  Is the idea that someone would do a Seek, consume the results using Next, then do another Seek from that point using the same iterator?

Maybe we should provide an accessor in Iterator to get the current Node setting, so they can see this outcome more directly?

File: reverse_iter.go [hunk 3]
```diff
@@ -56,9 +66,19 @@ func (ri *ReverseIterator) SeekReverseLowerBound(key []byte) {
...
+		ri.expandedParents = make(map[*Node]struct{})
+	}
+
 	found := func(n *Node) {
 		ri.i.node = n
 		ri.i.stack = append(ri.i.stack, edges{edge{node: n}})
+		// We need to mark this node as expanded in advance too otherwise the
+		// iterator will attempt to walk all of it's children even though they are
+		// greater than the lower bound we have found. We've expanded it in the
+		// sense that all of it's children that we want to walk are already in the
```
Comment (ncabatoff) [inline reverse_iter.go:79]:
```suggestion
		// sense that all of its children that we want to walk are already in the
```

File: reverse_iter.go [hunk 4]
```diff
@@ -84,28 +104,61 @@ func (ri *ReverseIterator) SeekReverseLowerBound(key []byte) {
...
+			// Firstly, if it's an exact match, we're done!
+			if bytes.Equal(n.leaf.key, key) {
+				found(n)
 				return
 			}
-			found(n)
-			return
+
+			// It's not so this node's leaf value must be lower and could still be a
+			// valide contender for reverse lower bound.
```
Comment (ncabatoff) [inline reverse_iter.go:128]:
```suggestion
			// valid contender for reverse lower bound.
```

File: reverse_iter.go [hunk 5]
```diff
@@ -84,28 +104,61 @@ func (ri *ReverseIterator) SeekReverseLowerBound(key []byte) {
...
+			if len(n.edges) == 0 {
+				// This leaf is the lower bound.
+				found(n)
+				return
+			}
+
+			// Finally, this leaf is internal (has children) so we'll keep searching,
+			// but we need to add it to the iterator's stack since it has a leaf value
+			// that needs to be iterated over. It needs to be added to the stack
+			// before it's children below as it comes first.
```
Comment (ncabatoff) [inline reverse_iter.go:140]:
```suggestion
			// before its children below as it comes first.
```

File: reverse_iter.go [hunk 6]
```diff
@@ -84,28 +104,61 @@ func (ri *ReverseIterator) SeekReverseLowerBound(key []byte) {
...
+			ri.i.stack = append(ri.i.stack, edges{edge{node: n}})
+			// We also need to mark it as expanded since we'll be adding any of it's
```
Comment (ncabatoff) [inline reverse_iter.go:142]:
```suggestion
			// We also need to mark it as expanded since we'll be adding any of its
```

File: reverse_iter.go [hunk 7]
```diff
@@ -84,28 +104,61 @@ func (ri *ReverseIterator) SeekReverseLowerBound(key []byte) {
...
+			// relevant children below and so don't want the iterator to re-add them
+			// on it's way back up the stack.
```
Comment (ncabatoff) [inline reverse_iter.go:144]:
```suggestion
			// on its way back up the stack.
```

File: iradix_test.go [hunk 8]
```diff
@@ -1532,26 +1532,29 @@ func TestLenTxn(t *testing.T) {
...
-	mixedLenKeys := []string{
-		"a1",
-		"abc",
-		"barbazboo",
-		"foo",
-		"found",
-		"zap",
-		"zip",
-	}
+// these should be defined in order
```
Comment (ncabatoff) [inline iradix_test.go:1535]: My preference would be to see this data copied to the new test method rather than shared, but that's probably because I've had to maintain code before where the pattern of shared test data had over time resulted in a mess that no one understood enough to feel safe modifying.  I don't see that as very likely here, although I do think the new test method would be a little bit more readable if it had the data defined inline.

**Comment by banks** [comment]
I've found another panic while tweaking fuzz tests and ensuring full coverage of example tests for both lower bound methods.

I'll add an example and a fix for that.

File: iter.go (hunk 2 above)
Comment (ncabatoff) [reply iter.go:96]: We should also consider validating the Node update side-effect in tests.

**Review by ncabatoff — APPROVED** [review]
Changes are looking great!

**Comment by banks** [comment]
OK I _think_ those last two commits fix up the remaining issues i've found. I used code coverage reports when running single tests to evaluate the coverage of both the example tests and the fuzz tests to ensure they were exercising every remaining code path. The fixes include:

 - [x] Reduce the entropy of Fuzz tests - they were too random before so that it was extremely rare that the keys generated shared much of a prefix and so didn't actually exercise as many of the paths through the logic. Also allow them to include zero length key which found a bunch more issues.
 - [x] Fix a panic the fuzz tests found in `SeekLowerBound` in one particular case that the examples didn't cover. There is now an example test that covers that panic too.
 - [x] Fix several issues in the Fuzz tests that were incorrect when zero-length keys were used
 - [x] Fix a further bug in `SeekReverseLowerBound` that caused missed keys on iteration - added an example based on the case found by fuzz tests for this that now passes.
 - [x] Remove the "non root" fuzz test for `SeekReverseLowerBound` since coverage suggest the single one now does exercise all relevant cases - the rationale given I think no longer makes sense because the implementation has changed to support internal leaves and to recurse to the max sub-tree during iteration rather than during seek. I couldn't see a case where non-root would inherently exercise paths that root-based tests did not with the right inputs and coverage seems to confirm that.
 - [x] Ran both remaining fuzz tests at least 20 times each locally without failures. 

Thanks for the review @ncabatoff I'll go through your feedback again as I think you had some good points but wanted to get this up today and have this PR in a shape where I _think_ I have some confidence in it's thoroughness again!

**Comment by banks** [comment]
Fuzz tests run 1000 times each locally without a failure after last refactoring:

```
$ go test -v -run Fuzz -count=1000 | rg '^(---|PASS|ok)'
--- PASS: TestIterateLowerBoundFuzz (0.00s)
--- PASS: TestReverseIterator_SeekReverseLowerBoundFuzz (0.00s)
...
--- PASS: TestIterateLowerBoundFuzz (0.00s)
--- PASS: TestReverseIterator_SeekReverseLowerBoundFuzz (0.00s)
PASS
ok  	github.com/hashicorp/go-immutable-radix	6.527s
```

File: reverse_iter.go [hunk 9]
```diff
@@ -71,41 +83,74 @@ func (ri *ReverseIterator) SeekReverseLowerBound(key []byte) {
...
+			// Prefix is smaller than search prefix, that means there is no lower
+			// bound. But we are looking in reverse, so the reverse lower bound will
+			// be the largest leaf under this subtree, since it is the value that
+			// would come right before the current search prefix if it were in the
+			// tree. So we need to follow the maximum path in this subtree to find it.
+			// Note that this is exactly what the iterator will already do if it find
+			// a node in the stack that has _not_ been marked as expanded so in this
+			// one case we don't call `found` and just let the iterator do its
+			// expansion and recursion through all the children.
+			ri.i.node = n
```
Comment (banks) [inline reverse_iter.go:95]: this is pointless I missed removing it

**Review by lgfa29 — APPROVED** [review]
The changes look great. Thanks for updating `ReverseIterator` as well 🎉

**Comment by thaJeztah** [comment]
Thanks!
